//! # Layout
//!
//! implements the layout algorithm.
use std::{
    any::TypeId,
    ops::{Deref, DerefMut, Div},
    sync::Arc,
};

use derive_more as d;
use glam::{U16Vec2, Vec2, Vec2Swizzles, u16vec2};
use hecs::{CommandBuffer, Component, ComponentError, Entity, View, World};
use manatui_utils::{Ecs, EcsMut};
use ratatui::{
    buffer::Buffer,
    layout::{Direction, Margin, Rect},
    style::{Style, Styled},
    widgets::{Padding, Widget},
};
use ratatui::{layout::Offset, widgets::StatefulWidget};
use tracing::instrument;
pub use tui_scrollview::{ScrollView, ScrollViewState};

/// trait for rendering elements through a shared reference. this is automatically implemented
/// for anything that implements [`Widget`], [`Clone`] and [`Component`]
pub trait ElWidget<M>: std::fmt::Debug + Component {
    /// the state type
    type State: ?Sized + Default + Component + Clone;
    /// render the element through the shared reference. clones internally
    fn render_element(&self, area: Rect, buf: &mut Buffer, state: &mut Self::State);
    /// sets the style of a widget
    fn set_style(&mut self, style: Style);
    /// gets the style of a widget
    fn get_style(&self) -> Style;
}

/// marker for [`ElWidget`] trait.
pub struct WidgetMarker;
/// marker for [`ElWidget`] trait.
pub struct StatefulWidgetMarker;

impl<W: 'static> ElWidget<WidgetMarker> for W
where
    W: Widget + Styled<Item = W> + Clone + std::fmt::Debug + Component,
{
    type State = ();

    fn render_element(&self, area: Rect, buf: &mut Buffer, _: &mut Self::State) {
        self.clone().render(area, buf);
    }

    fn set_style(&mut self, style: Style) {
        *self = Styled::set_style(self.clone(), style);
    }

    fn get_style(&self) -> Style {
        self.style()
    }
}

/// # `Stateful` wrapper
///
/// makes the widget render with its [`StatefulWidget`] implementation. the state
/// should be added as a component.
#[derive(Debug, Clone, Default, derive_more::Deref, derive_more::DerefMut)]
pub struct Stateful<W>(W);

impl<W> ElWidget<StatefulWidgetMarker> for Stateful<W>
where
    W: StatefulWidget + Styled<Item = W> + Clone + std::fmt::Debug + Component,
    W::State: Default + Component + Clone,
{
    type State = <W as StatefulWidget>::State;

    fn render_element(&self, area: Rect, buf: &mut Buffer, state: &mut Self::State) {
        self.0.clone().render(area, buf, state);
    }

    fn set_style(&mut self, style: Style) {
        self.0 = Styled::set_style(self.0.clone(), style);
    }

    fn get_style(&self) -> Style {
        self.0.style()
    }
}

/// extension trait for wrapping widgets in the [`Stateful`] wrapper.
pub trait IntoStateful: StatefulWidget + Sized {
    /// turns a type that implements [`StatefulWidget`] into a [`Stateful`]
    fn stateful(self) -> Stateful<Self> {
        Stateful(self)
    }
}

impl<W> IntoStateful for W where W: StatefulWidget + Sized {}

/// Context struct that drives the layout engine.
///
/// # Usage
///
/// - [`ElementCtx::deref`] derefs to the inner [`hecs::World`]
/// - [`ElementCtx::spawn_ui`] takes a builder generated by the [`ui`][crate::ui::ui] function and spawns it and all its children
/// - [`ElementCtx::calculate_layout`] takes the root element and calculates sizes and positions.
/// - [`ElementCtx::render`] renders the tree to the provided buffer.
///
/// # Example
///
/// ```
/// # use manatui_layout::prelude::*;
/// # use ratatui::buffer::Buffer;
/// # use ratatui::layout::Rect;
///
/// let mut ctx = ElementCtx::new();
///
/// let root = ui(Text::raw("hello world"));
/// let root = ctx.spawn_ui(root);
///
/// # let mut buf = Buffer::empty(Rect::new(0, 0, 50, 24));
/// // `&mut Buffer` from ratatui
/// ctx.calculate_layout(root, buf.area).unwrap();
/// ctx.render(root, buf.area, &mut buf);
/// ```
///
/// see [`ui module`][crate::ui] for more details.
#[derive(Default, d::Deref, d::DerefMut)]
pub struct ElementCtx {
    #[deref]
    #[deref_mut]
    pub(crate) world: World,
    pub(crate) node_post_render_systems:
        Vec<<NodePostRenderSchedule as ElementSchedule>::SchedulePointer>,
}

/// Marker struct for the `NodePostRender` schedule. Systems in this schedule
/// run after every node render.
pub struct NodePostRenderSchedule;

/// System schedule trait
///
/// Available schedules:
/// - [`NodePostRenderSchedule`] runs after every node render.
pub trait ElementSchedule {
    /// The type of the system function pointer.
    type SchedulePointer;

    /// extractor method for the systems collection.
    fn systems_schedule_mut(ctx: &mut ElementCtx) -> &mut Vec<Self::SchedulePointer>;
}

impl ElementSchedule for NodePostRenderSchedule {
    type SchedulePointer = fn(&mut World, Rect, &mut Buffer, Element);

    fn systems_schedule_mut(ctx: &mut ElementCtx) -> &mut Vec<Self::SchedulePointer> {
        &mut ctx.node_post_render_systems
    }
}

impl Ecs for ElementCtx {}
impl EcsMut for ElementCtx {}

#[derive(hecs::Query)]
struct NodeQuery<'a> {
    props: &'a mut Props,
    width: &'a Width,
    height: &'a Height,
    padding: &'a Padding,
    children: &'a Children,
    direction: &'a Direction,
    gap: &'a Gap,
    main_justify: &'a MainJustify,
    cross_justify: &'a CrossJustify,
    max_width: Option<&'a MaxWidth>,
    max_height: Option<&'a MaxHeight>,
    entity: Entity,
}

impl<'a> NodeQuery<'a> {
    #[inline(always)]
    fn compute_inner_size(&self) -> U16Vec2 {
        let gap_space = self.children.len().saturating_sub(1) as u16 * **self.gap;
        let inner_size = self.props.inner_size_from_padding(self.padding);
        let mut inner_size = axify(inner_size, *self.direction);
        inner_size.main_axis = inner_size.main_axis.saturating_sub(gap_space);

        inner_size.to_u16vec2(*self.direction)
    }
}

macro_rules! extract {
    ($view:ident, $el:expr) => {
        unsafe { $view.get_unchecked($el).ok_or(ComponentError::NoSuchEntity) }
    };
}

macro_rules! axis_mut {
    (cross: $value:expr, $dir:expr) => {
        match $dir {
            Direction::Horizontal => &mut $value.y,
            Direction::Vertical => &mut $value.x,
        }
    };
}

impl ElementCtx {
    /// create an empty context.
    pub fn new() -> Self {
        Self::default()
    }

    /// Adds a system to the specified `S` Schedule. For a list of schedules,
    /// see [`ElementSchedule`].
    pub fn add_system<S: ElementSchedule>(&mut self, fn_ptr: S::SchedulePointer) {
        S::systems_schedule_mut(self).push(fn_ptr);
    }

    fn calculate_fit_sizes(
        &self,
        view: &View<'_, NodeQuery<'_>>,
        element: Element,
    ) -> Result<(), ComponentError> {
        let el = extract!(view, element)?;

        let gap_space = el.children.len().saturating_sub(1) as u16 * **el.gap;
        let mut space_used = AxisSizes::default();

        let max_width = el.max_width.unwrap_or(&MaxWidth(Size::Fit));
        let max_height = el.max_height.unwrap_or(&MaxHeight(Size::Fit));
        let max_size = u16vec2(
            *max_width.as_fixed().unwrap_or(&u16::MAX),
            *max_height.as_fixed().unwrap_or(&u16::MAX),
        );

        el.children
            .iter()
            .try_for_each(|child| -> Result<(), ComponentError> {
                self.calculate_fit_sizes(view, child)?;

                let child = extract!(view, child)?;
                space_used = space_used.increase(child.props.size, *el.direction);
                Ok(())
            })?;

        space_used = space_used.pad(*el.padding, *el.direction);
        space_used.main_axis += gap_space;
        let space_used = space_used.to_u16vec2(*el.direction);

        let size = u16vec2(
            *el.width.as_fixed().unwrap_or(&space_used.x),
            *el.height.as_fixed().unwrap_or(&space_used.y),
        );
        el.props.size = size.clamp(U16Vec2::ZERO, max_size);

        tracing::trace!(target: "manatui::fit", ?element, ?el.props.size);
        Ok(())
    }
    fn sum_space_used(&self, elements: &[Element]) -> U16Vec2 {
        elements
            .iter()
            .copied()
            .flat_map(|child| self.world.get::<&Props>(child))
            .map(|props| props.size)
            .sum::<U16Vec2>()
    }
    fn sum_space_used_with_view(&self, view: &View<NodeQuery>, elements: &[Element]) -> U16Vec2 {
        elements
            .iter()
            .copied()
            .flat_map(|child| unsafe { view.get_unchecked(child) })
            .map(|el| el.props.size)
            .sum::<U16Vec2>()
    }
    fn calculate_grow_sizes(
        &self,
        view: &View<'_, NodeQuery<'_>>,
        element: Element,
        is_root: bool,
        area: Rect,
    ) -> Result<(), ComponentError> {
        let el = extract!(view, element)?;
        if is_root {
            // if the root element is set to grow, we want it to take up the entire
            // screen.
            if el.width.is_grow() {
                el.props.size.x = area.width;
            }
            if el.height.is_grow() {
                el.props.size.y = area.height;
            }
        }

        let inner_size = el.compute_inner_size();

        #[derive(Debug)]
        struct GrowEntry {
            can_grow: bool,
            entity: Element,
            size: u16,
            max_size: u16,
        }

        let mut inner_size_float_max = inner_size.as_vec2();
        let mut inner_size_float = inner_size.as_vec2();
        let mut buffer = el
            .children
            .iter()
            .flat_map(|child| -> Result<_, ComponentError> {
                let child = extract!(view, child)?;
                let max_width = child.max_width.unwrap_or(&MaxWidth(Size::Fit));
                let max_height = child.max_height.unwrap_or(&MaxHeight(Size::Fit));
                let max_size = u16vec2(
                    max_width
                        .compute_from_parent(&mut inner_size_float_max.x)
                        .unwrap_or(u16::MAX),
                    max_height
                        .compute_from_parent(&mut inner_size_float_max.y)
                        .unwrap_or(u16::MAX),
                );

                // cross axis calculation
                let cross_axis = *(*child.width, *child.height).cross_axis(*el.direction);
                if cross_axis.is_grow() {
                    let cross_axis = child.props.size.cross_axis_mut(*el.direction);
                    let cross_axis_max_size = *(*max_width, *max_height).cross_axis(*el.direction);
                    let cross_axis_inner_size = inner_size_float.cross_axis_mut(*el.direction);
                    let cross_axis_max_size_computed =
                        cross_axis_max_size.compute_from_parent(cross_axis_inner_size);
                    match cross_axis_max_size_computed {
                        Some(value) => {
                            *cross_axis = value;
                        }
                        None => {
                            *cross_axis = *cross_axis_inner_size as u16;
                        }
                    }
                    *cross_axis = (*cross_axis).clamp(0u16, *max_size.cross_axis(*el.direction));
                }

                let main_axis = child.props.size.main_axis_mut(*el.direction);
                let main_axis_size = *(*child.width, *child.height).main_axis(*el.direction);
                let main_axis_size_computed = main_axis_size
                    .compute_from_parent(inner_size_float.main_axis_mut(*el.direction));
                if let Some(value) = main_axis_size_computed {
                    *main_axis = value;
                }
                let can_grow = main_axis_size.is_grow();

                Ok(GrowEntry {
                    can_grow,
                    entity: child.entity,
                    size: *main_axis,
                    max_size: *max_size.main_axis(*el.direction),
                })
            })
            .collect::<Vec<_>>();

        buffer.sort_by_key(|entry| entry.size);

        let space_used = self.sum_space_used_with_view(view, el.children);

        let remaining_size = inner_size.saturating_sub(space_used);
        let remaining_size = axify(remaining_size, *el.direction);
        let mut remaining = remaining_size.main_axis;

        let mut search_start = 0;
        let grow_count = buffer.iter().filter(|e| e.can_grow).count();

        #[expect(clippy::manual_checked_ops)]
        if grow_count != 0 {
            while remaining != 0 {
                // find smallest and second smallest element
                let smallest = buffer
                    .array_windows::<2>()
                    .skip(search_start)
                    .position(|[a, b]| b.size > a.size);

                let Some(smallest) = smallest else {
                    for entry in buffer.iter() {
                        if !entry.can_grow {
                            continue;
                        }
                        remaining += entry.size.saturating_sub(entry.max_size);
                    }
                    let split = remaining as usize / grow_count;
                    let split = split as u16;
                    for entry in buffer.iter_mut() {
                        if !entry.can_grow {
                            continue;
                        }
                        entry.size += split;
                    }

                    let used = split * grow_count as u16;
                    remaining = remaining.saturating_sub(used);
                    for entry in buffer.iter_mut() {
                        if remaining == 0 {
                            break;
                        }
                        if !entry.can_grow {
                            continue;
                        }
                        entry.size += 1;
                        remaining -= 1;
                    }
                    break;
                };
                let second_smallest = smallest + 1;
                search_start = second_smallest;
                let smallest_size = buffer[smallest].size;
                let second_smallest_size = buffer[second_smallest].size;
                for entry in buffer.iter_mut() {
                    if entry.size == smallest_size {
                        let difference = second_smallest_size.saturating_sub(entry.size);
                        let difference = difference.clamp(0, remaining);
                        entry.size += difference;
                        if entry.can_grow {
                            remaining = remaining.saturating_sub(difference);
                        }
                    }
                }
            }
        }

        for entry in buffer {
            if !entry.can_grow {
                continue;
            }
            let child = extract!(view, entry.entity)?;
            let props = AxisSizes::from_u16vec2(child.props.size, *el.direction)
                .with_main(entry.size.clamp(0, entry.max_size));
            child.props.size = props.to_u16vec2(*el.direction);
        }

        for child in el.children.iter() {
            self.calculate_grow_sizes(view, child, false, area)?;
        }

        Ok(())
    }
    fn calculate_positions(
        &self,
        view: &View<NodeQuery>,
        root: Element,
    ) -> Result<(), ComponentError> {
        let el = extract!(view, root)?;
        let children = el.children.clone();
        let space_used = self.sum_space_used_with_view(view, &children);
        let space_used = axify(space_used, *el.direction).main_axis;
        let space_used = space_used + **el.gap * children.len().saturating_sub(1) as u16;
        let inner_size = el.props.size.saturating_sub(u16vec2(
            el.padding.left + el.padding.right,
            el.padding.top + el.padding.bottom,
        ));
        let remaining_size = axify(el.props.size, *el.direction)
            .shrink(*el.padding, *el.direction)
            .main_axis
            .saturating_sub(space_used);

        #[derive(Default)]
        struct AlignValues {
            start: u16,
            inbetween: u16,
            remainder: u16,
        }

        impl AlignValues {
            fn tick_rem(&mut self) -> u16 {
                match self.remainder {
                    0 => 0,
                    1.. => {
                        self.remainder -= 1;
                        1
                    }
                }
            }
        }

        let mut align = match el.main_justify {
            MainJustify::Start => AlignValues::default(),
            MainJustify::Center => AlignValues {
                start: remaining_size / 2,
                inbetween: 0,
                remainder: 0,
            },
            MainJustify::SpaceBetween if children.is_empty() => AlignValues::default(),
            MainJustify::SpaceBetween => {
                let div_by = (children.len().saturating_sub(1)) as u16;
                match remaining_size.checked_div(div_by) {
                    Some(space) => {
                        let space_rem = remaining_size % div_by;
                        AlignValues {
                            start: 0,
                            inbetween: space,
                            remainder: space_rem,
                        }
                    }
                    None => AlignValues::default(),
                }
            }
            MainJustify::SpaceAround if children.is_empty() => AlignValues::default(),
            MainJustify::SpaceAround => {
                let div_by = (children.len() * 2) as u16;
                match remaining_size.checked_div(div_by) {
                    None => AlignValues::default(),
                    Some(space) => {
                        let space_rem = remaining_size % div_by;
                        AlignValues {
                            start: space,
                            inbetween: space * 2,
                            remainder: space_rem,
                        }
                    }
                }
            }
            MainJustify::SpaceEvenly if children.is_empty() => AlignValues::default(),
            MainJustify::SpaceEvenly => {
                let div_by = (children.len() * 2) as u16 + 2;
                match remaining_size.checked_div(div_by) {
                    None => AlignValues::default(),
                    Some(space) => AlignValues {
                        start: space * 2,
                        inbetween: space * 2,
                        remainder: 0,
                    },
                }
            }
            MainJustify::End => AlignValues {
                start: remaining_size,
                inbetween: 0,
                remainder: 0,
            },
        };

        children
            .iter()
            .try_for_each(|child| -> Result<(), ComponentError> {
                {
                    let child = unsafe {
                        view.get_unchecked(child)
                            .ok_or(ComponentError::NoSuchEntity)?
                    };
                    let child_props = child.props;
                    child_props.position = el.props.position;
                    match el.direction {
                        Direction::Horizontal => child_props.position.x += align.start,
                        Direction::Vertical => child_props.position.y += align.start,
                    }
                    child_props.position += u16vec2(el.padding.left, el.padding.top);
                    align.start = increase_axis(align.start, *el.direction, child_props.size);
                    match (el.cross_justify, el.direction) {
                        (CrossJustify::Start, _) => {}
                        (CrossJustify::Center, Direction::Horizontal) => {
                            child_props.position.y +=
                                inner_size.y.saturating_sub(child_props.size.y).div(2);
                        }
                        (CrossJustify::Center, Direction::Vertical) => {
                            child_props.position.x +=
                                inner_size.x.saturating_sub(child_props.size.x).div(2);
                        }
                        (CrossJustify::End, Direction::Horizontal) => {
                            child_props.position.y +=
                                inner_size.y.saturating_sub(child_props.size.y);
                        }
                        (CrossJustify::End, Direction::Vertical) => {
                            child_props.position.x +=
                                inner_size.x.saturating_sub(child_props.size.x);
                        }
                    }
                    align.start += **el.gap + align.inbetween + align.tick_rem();
                }
                self.calculate_positions(view, child)?;
                Ok(())
            })?;

        Ok(())
    }
    /// runs the layout calculation step. takes the root element as the argument.
    ///
    /// # Error
    ///
    /// this will error if any element index is invalid. this can only happen if you manually despawn
    /// entities using [`hecs::World::despawn`] or other such methods.
    pub fn calculate_layout(&mut self, element: Element, area: Rect) -> Result<(), ComponentError> {
        {
            let origin = u16vec2(area.x, area.y);
            let mut root_props = self.get::<&mut Props>(element)?;
            root_props.position = origin;
        }

        let root_size = u16vec2(area.width, area.height);
        {
            let mut query = self.world.query::<NodeQuery>();
            let view = query.view();
            self.calculate_fit_sizes(&view, element)?;
            self.calculate_grow_sizes(&view, element, true, area)?;
            self.calculate_positions(&view, element)?;
        }
        self.layout_postprocess();
        Ok(())
    }
    fn layout_postprocess(&mut self) {
        for (props, scrollview, padding) in
            self.query_mut::<(&mut Props, &mut ScrollView, Option<&Padding>)>()
        {
            let inner_size = props.inner_size_from_padding(padding.unwrap_or(&Padding::ZERO));
            *scrollview = ScrollView::new(ratatui::layout::Size {
                width: inner_size.x,
                height: inner_size.y,
            });
        }
    }
    /// renders the tree.
    ///
    /// also see [`ratatui::prelude::Rect`], [`ratatui::prelude::Buffer`]
    pub fn render(&mut self, root: Element, area: Rect, buf: &mut Buffer) {
        // render self
        self.render_impl(root, area, buf, Offset { x: 0, y: 0 });
    }

    fn render_impl(&mut self, root: Element, area: Rect, buf: &mut Buffer, offset: Offset) {
        let mut query = self.world.query_one::<(&mut Props, &Children)>(root);
        let (props, children) = query.get().unwrap();
        let area = props.split_area(area, offset);

        (props.render)(self, root, area, buf);
        let children = children.clone();
        drop(query);
        let ElementCtx {
            world,
            node_post_render_systems,
        } = self;
        for system in node_post_render_systems {
            system(world, area, buf, root);
        }

        // render children

        if let Ok(mut scrollview) = self.remove_one::<ScrollView>(root) {
            {
                for child in children.iter() {
                    self.render_impl(
                        child,
                        scrollview.area(),
                        scrollview.buf_mut(),
                        Offset {
                            x: offset.x - i32::from(area.x),
                            y: offset.y - i32::from(area.y),
                        },
                    );
                }
            };
            {
                let mut scroll_state = self.get::<&mut ScrollViewState>(root);
                let mut default_scroll_state = ScrollViewState::default();
                scrollview.clone().render(
                    area,
                    buf,
                    scroll_state
                        .as_deref_mut()
                        .unwrap_or(&mut default_scroll_state),
                );
            }

            _ = self.insert_one(root, scrollview);
        } else {
            for child in children.iter() {
                self.render_impl(child, area, buf, offset);
            }
        }
    }
}

fn increase_axis(init: u16, dir: Direction, size: U16Vec2) -> u16 {
    match dir {
        Direction::Horizontal => init + size.x,
        Direction::Vertical => init + size.y,
    }
}

#[derive(
    Debug, Clone, Copy, Default, d::Sub, d::SubAssign, d::Add, d::AddAssign, d::Sum, PartialEq, Eq,
)]
struct AxisSizes {
    main_axis: u16,
    cross_axis: u16,
}

const fn axify(vec: U16Vec2, dir: Direction) -> AxisSizes {
    AxisSizes::from_u16vec2(vec, dir)
}

/// convention: x is cross axis, y is main axis
const fn into_axis(vec: U16Vec2, dir: Direction) -> U16Vec2 {
    match dir {
        Direction::Horizontal => u16vec2(vec.y, vec.x),
        Direction::Vertical => vec,
    }
}

impl AxisSizes {
    #[inline(always)]
    fn min(self, other: AxisSizes) -> AxisSizes {
        AxisSizes {
            main_axis: self.main_axis.min(other.main_axis),
            cross_axis: self.cross_axis.min(other.cross_axis),
        }
    }
    #[inline(always)]
    fn max(self, other: AxisSizes) -> AxisSizes {
        AxisSizes {
            main_axis: self.main_axis.max(other.main_axis),
            cross_axis: self.cross_axis.max(other.cross_axis),
        }
    }
    const fn with_main(mut self, value: u16) -> Self {
        self.main_axis = value;
        self
    }
    #[inline(always)]
    const fn from_u16vec2(value: U16Vec2, dir: Direction) -> Self {
        match dir {
            Direction::Horizontal => Self {
                main_axis: value.x,
                cross_axis: value.y,
            },
            Direction::Vertical => Self {
                main_axis: value.y,
                cross_axis: value.x,
            },
        }
    }
    #[inline(always)]
    const fn pad(self, padding: Padding, dir: Direction) -> AxisSizes {
        match dir {
            Direction::Horizontal => AxisSizes {
                main_axis: self.main_axis + padding.left + padding.right,
                cross_axis: self.cross_axis + padding.top + padding.bottom,
            },
            Direction::Vertical => AxisSizes {
                main_axis: self.main_axis + padding.top + padding.bottom,
                cross_axis: self.cross_axis + padding.left + padding.right,
            },
        }
    }
    #[inline(always)]
    const fn shrink(self, padding: Padding, dir: Direction) -> AxisSizes {
        match dir {
            Direction::Horizontal => AxisSizes {
                main_axis: self.main_axis.saturating_sub(padding.left + padding.right),
                cross_axis: self.cross_axis.saturating_sub(padding.top + padding.bottom),
            },
            Direction::Vertical => AxisSizes {
                main_axis: self.main_axis.saturating_sub(padding.top + padding.bottom),
                cross_axis: self.cross_axis.saturating_sub(padding.left + padding.right),
            },
        }
    }
    #[inline(always)]
    fn increase(self, by: U16Vec2, dir: Direction) -> AxisSizes {
        match dir {
            Direction::Horizontal => AxisSizes {
                main_axis: self.main_axis + by.x,
                cross_axis: self.cross_axis.max(by.y),
            },
            Direction::Vertical => AxisSizes {
                main_axis: self.main_axis + by.y,
                cross_axis: self.cross_axis.max(by.x),
            },
        }
    }
    #[inline(always)]
    const fn to_u16vec2(self, dir: Direction) -> U16Vec2 {
        match dir {
            Direction::Horizontal => u16vec2(self.main_axis, self.cross_axis),
            Direction::Vertical => u16vec2(self.cross_axis, self.main_axis),
        }
    }
}

/// type alias for [`hecs::Entity`]
pub type Element = Entity;

/// marker for any element created via [`ui`][crate::ui::ui]. you can use this query elements in the tree.
/// see [`hecs::World::query`] and [`hecs::World::query_mut`] for details.
pub struct TuiElMarker;

///
#[derive(Debug, Clone, Copy)]
pub struct Props {
    ///
    pub size: U16Vec2,
    ///
    pub position: U16Vec2,
    ///
    pub render: fn(&ElementCtx, Element, Rect, &mut Buffer),
    ///
    pub set_style: fn(&mut World, Element, Style),
    ///
    pub get_style: fn(&World, Element) -> Option<Style>,
    ///
    pub typeid: TypeId,
}

impl Props {
    #[inline]
    pub(crate) const fn inner_size_from_padding(&self, padding: &Padding) -> U16Vec2 {
        self.inner_size(Margin {
            horizontal: padding.left + padding.right,
            vertical: padding.top + padding.bottom,
        })
    }
    #[inline]
    const fn inner_size(&self, margin: Margin) -> U16Vec2 {
        self.size
            .saturating_sub(u16vec2(margin.horizontal, margin.vertical))
    }
}

impl Props {
    fn split_area(&self, area: Rect, offset: Offset) -> Rect {
        area.intersection(Rect {
            // DONE: implement position
            x: self.position.x.saturating_add_signed(offset.x as i16),
            y: self.position.y.saturating_add_signed(offset.y as i16),
            width: self.size.x,
            height: self.size.y,
        })
    }
}

/// defines the [`Size`] on the x axis.
/// defaults to: `Size::Fit`
#[derive(Debug, Clone, Copy, Default, d::Deref)]
pub struct Width(pub Size);

/// defines the [`Size`] on the y axis.
/// defaults to: `Size::Fit`
#[derive(Debug, Clone, Copy, Default, d::Deref)]
pub struct Height(pub Size);

/// defines the maximum [`Size`] on the x axis.
#[derive(Debug, Clone, Copy, d::Deref)]
pub struct MaxWidth(pub Size);

/// defines the maximum [`Size`] on the y axis.
#[derive(Debug, Clone, Copy, d::Deref)]
pub struct MaxHeight(pub Size);

macro_rules! impl_sizing_functions {
    ($ty:ty) => {
        impl $ty {
            /// create a [`Size::Fixed`] value
            pub const fn fixed(value: u16) -> Self {
                Self(Size::Fixed(value))
            }
            /// create a [`Size::Fit`] value
            pub const fn fit() -> Self {
                Self(Size::Fit)
            }
            /// create a [`Size::Grow`] value
            pub const fn grow() -> Self {
                Self(Size::Grow)
            }

            /// create a [`Size::Percentage`] value
            pub const fn percentage(value: u8) -> Self {
                Self(Size::Percentage(value))
            }
        }
    };
}

impl_sizing_functions!(Width);
impl_sizing_functions!(Height);
impl_sizing_functions!(MaxWidth);
impl_sizing_functions!(MaxHeight);

/// defines the gap on the main axis between child elements.
/// defaults to: 0`
///
/// # Example
///
/// Gap 2
/// ```plaintext
/// ╭parent──────────╮
/// │╭──╮  ╭──╮  ╭──╮│
/// ││  │  │  │  │  ││
/// │╰──╯  ╰──╯  ╰──╯│
/// ╰────────────────╯
/// ```
///
/// Gap 0
/// ```plaintext
/// ╭parent──────╮
/// │╭──╮╭──╮╭──╮│
/// ││  ││  ││  ││
/// │╰──╯╰──╯╰──╯│
/// ╰────────────╯
/// ```
#[derive(Debug, Clone, Copy, Default, d::Deref)]
pub struct Gap(pub u16);

/// holds a list of entity ids to the element's children. this component is added automatically.
/// you can use this to iterate the children of an element like this
///
/// ```rust
/// # use manatui_layout::prelude::*;
/// # let mut ctx = ElementCtx::new();
/// # let root = ui(Block::new())
/// #     .with((Width(Size::Grow), Height(Size::Fixed(40))))
/// #     .children((
/// #         ui(Block::new()),
/// #         ui(Block::new())
/// #     ));
/// # let root = ctx.spawn_ui(root);
/// let children = ctx.get::<&Children>(root).unwrap();
/// for child in children.iter() {
///     let width = ctx.get::<&Width>(*child);
/// }
/// ```
#[derive(Debug, Clone, Default)]
pub enum Children {
    /// Thread-safe reference counted pointer to a vector of [`Element`]s
    Some(Arc<Vec<Element>>),
    /// no children. avoids Arc allocation
    #[default]
    None,
}

impl Children {
    fn iter<'a>(&'a self) -> ChildrenIter<'a> {
        self.into_iter()
    }
}

impl Deref for Children {
    type Target = [Element];

    fn deref(&self) -> &Self::Target {
        match self {
            Children::Some(items) => items.as_ref(),
            Children::None => &[],
        }
    }
}

/// Iterator over children IDs. this yields owned values since [`Elements`] is Copy.
pub struct ChildrenIter<'a> {
    inner: std::iter::Copied<std::slice::Iter<'a, Element>>,
}

impl<'a> Iterator for ChildrenIter<'a> {
    type Item = Element;

    fn next(&mut self) -> Option<Self::Item> {
        self.inner.next()
    }
}

impl<'a> IntoIterator for &'a Children {
    type Item = Element;

    type IntoIter = ChildrenIter<'a>;

    fn into_iter(self) -> Self::IntoIter {
        let inner = self.deref().iter().copied();
        ChildrenIter { inner }
    }
}

#[inline(always)]
fn cross_size(dir: Direction, x: Width, y: Height) -> Size {
    match dir {
        Direction::Horizontal => *y,
        Direction::Vertical => *x,
    }
}
#[inline(always)]
fn main_size(dir: Direction, x: Width, y: Height) -> Size {
    match dir {
        Direction::Horizontal => *x,
        Direction::Vertical => *y,
    }
}

/// defines the sizing strategy for an element.
#[derive(Default, Clone, Copy, Debug)]
pub enum Size {
    /// the element will be exactly `x` cells in size, clamped to it's parent's size.
    Fixed(u16),
    #[default]
    /// the element will grow to fit it's children, up to it's own parent's size
    Fit,
    /// the element will grow to fill it's parent, following a water-filling strategy, i.e. the smallest elements grow first.
    Grow,
    /// the element will be a percentage of it's parent size.
    Percentage(u8),
}

#[bon::bon]
impl Size {
    const fn compute_from_parent(self, parent_size: &mut f32) -> Option<u16> {
        match self {
            Size::Fixed(f) => Some(f),
            Size::Fit => None,
            Size::Grow => None,
            Size::Percentage(p) => {
                let size = (p as f64) * *parent_size as f64 / 100.0;
                match size.fract() {
                    0.0..0.5 => {
                        let size = size.round();
                        Some(size as u16)
                    }
                    fract @ 0.5.. => {
                        let size = size.round();
                        *parent_size -= fract as f32;
                        Some(size as u16)
                    }
                    _ => unreachable!(),
                }
            }
        }
    }
    #[builder]
    const fn apply(self, to: u16, parent_size: Option<u16>, space_used: Option<u16>) -> u16 {
        match (self, parent_size, space_used) {
            (Size::Fixed(f), _, _) => f,
            (Size::Percentage(p), Some(container), _) => {
                let size = (p as f64) * container as f64 / 100.0;
                let size = size.round();
                size as u16
            }
            (Size::Fit | Size::Grow, _, Some(space_used)) => space_used,
            _ => to,
        }
    }
}

/// defines the alignment strategy on the main axis.
#[derive(Default, Clone, Copy, Debug, strum::EnumIter)]
pub enum MainJustify {
    /// aligns the items toward the start of the container.
    ///
    /// ```plaintext
    /// ╭Start─────────────────╮
    /// │╭──╮╭──╮╭──╮          │
    /// ││#0││#1││#2│          │
    /// │╰──╯╰──╯╰──╯          │
    /// ╰──────────────────────╯
    /// ```
    #[default]
    Start,

    /// centers the items.
    ///
    /// ```plaintext
    /// ╭Center────────────────╮
    /// │     ╭──╮╭──╮╭──╮     │
    /// │     │#0││#1││#2│     │
    /// │     ╰──╯╰──╯╰──╯     │
    /// ╰──────────────────────╯
    /// ```
    Center,

    /// distributes the remaining space evenly between elements. inserts as much space between the elments as possible
    ///
    /// ```plaintext
    /// ╭SpaceBetween──────────╮
    /// │╭──╮     ╭──╮     ╭──╮│
    /// ││#0│     │#1│     │#2││
    /// │╰──╯     ╰──╯     ╰──╯│
    /// ╰──────────────────────╯
    /// ```
    SpaceBetween,

    /// distributes the remaining space evenly between elements such that there is an equal amount of space before
    /// and after each item.
    ///
    /// NOTE: this mode usually has poor results on small containers due to rounding issues.
    ///
    /// ```plaintext
    /// ╭SpaceAround───────────╮
    /// │ ╭──╮   ╭──╮   ╭──╮   │
    /// │ │#0│   │#1│   │#2│   │
    /// │ ╰──╯   ╰──╯   ╰──╯   │
    /// ╰──────────────────────╯
    /// ```
    SpaceAround,

    /// distributes the remaining space evenly between elements such that there is an equal amount of on each side of each item,
    /// accounting for the doubling of space that happens with [`Justify::SpaceAround`]
    ///
    /// NOTE: this mode usually has poor results on small containers due to rounding issues.
    ///
    /// ```plaintext
    /// ╭SpaceEvenly───────────╮
    /// │  ╭──╮  ╭──╮  ╭──╮    │
    /// │  │#0│  │#1│  │#2│    │
    /// │  ╰──╯  ╰──╯  ╰──╯    │
    /// ╰──────────────────────╯
    /// ```
    SpaceEvenly,

    /// aligns the items toward the end of the container.
    ///
    /// ```plaintext
    /// ╭End───────────────────╮
    /// │          ╭──╮╭──╮╭──╮│
    /// │          │#0││#1││#2││
    /// │          ╰──╯╰──╯╰──╯│
    /// ╰──────────────────────╯
    /// ```
    End,
}

#[derive(Default, Clone, Copy, Debug, strum::EnumIter)]
/// defines the alignment strategy on the cross axis.
pub enum CrossJustify {
    /// aligns the items toward the start of the container.
    #[default]
    Start,
    /// centers the items.
    Center,
    /// aligns the items toward the end of the container.
    End,
}

pub(crate) trait ManaComponent {
    fn run_postprocess(ctx: &mut ElementCtx, commands: &mut CommandBuffer);
}

/// equivalent to a `(MainJustify::Center, CrossJustify::Center)` bundle. this will make a container
/// center its children.
pub struct Center;

impl ManaComponent for Center {
    fn run_postprocess(ctx: &mut ElementCtx, _: &mut CommandBuffer) {
        // do not use the shared buffer
        let mut commands = CommandBuffer::new();
        for (node, _) in ctx.query_mut::<(Entity, &Center)>() {
            commands.insert_one(node, MainJustify::Center);
            commands.insert_one(node, CrossJustify::Center);
        }
        commands.run_on(ctx);
    }
}

impl Size {
    fn should_clamp(&self) -> bool {
        match self {
            Size::Fixed(_) => false,
            Size::Fit => false,
            Size::Grow => false,
            Size::Percentage(_) => false,
        }
    }
    fn is_grow(&self) -> bool {
        matches!(self, Size::Grow)
    }

    /// Returns `true` if the size is [`Percentage`].
    ///
    /// [`Percentage`]: Size::Percentage
    #[must_use]
    pub fn is_percentage(&self) -> bool {
        matches!(self, Self::Percentage(..))
    }

    /// Returns percentage value as `Some(u8)` if the size is [`Percentage`].
    ///
    /// [`Percentage`]: Size::Percentage
    #[must_use]
    pub fn as_percentage(&self) -> Option<&u8> {
        if let Self::Percentage(v) = self {
            Some(v)
        } else {
            None
        }
    }

    pub(crate) fn as_fixed(&self) -> Option<&u16> {
        if let Self::Fixed(v) = self {
            Some(v)
        } else {
            None
        }
    }
}

trait AxisExt {
    type El;
    fn main_axis(&self, dir: Direction) -> &Self::El;
    fn cross_axis(&self, dir: Direction) -> &Self::El;
}

trait AxisExtMut: AxisExt {
    fn main_axis_mut(&mut self, dir: Direction) -> &mut Self::El;
    fn cross_axis_mut(&mut self, dir: Direction) -> &mut Self::El;
}
macro_rules! impl_axis_ext {
    ($($type:ty => $el:ty),* $(,)?) => {
        $(
            impl AxisExt for $type {
                type El = $el;

                #[inline(always)]
                fn main_axis(&self, dir: Direction) -> &Self::El {
                    match dir {
                        Direction::Horizontal => &self.x,
                        Direction::Vertical => &self.y,
                    }
                }

                #[inline(always)]
                fn cross_axis(&self, dir: Direction) -> &Self::El {
                    match dir {
                        Direction::Horizontal => &self.y,
                        Direction::Vertical => &self.x,
                    }
                }
            }

            impl AxisExtMut for $type {
                #[inline(always)]
                fn main_axis_mut(&mut self, dir: Direction) -> &mut Self::El {
                    match dir {
                        Direction::Horizontal => &mut self.x,
                        Direction::Vertical => &mut self.y,
                    }
                }

                #[inline(always)]
                fn cross_axis_mut(&mut self, dir: Direction) -> &mut Self::El {
                    match dir {
                        Direction::Horizontal => &mut self.y,
                        Direction::Vertical => &mut self.x,
                    }
                }
            }
        )*
    };
}

impl_axis_ext!(
    U16Vec2 => u16,
    Vec2 => f32,
);

impl<T, U, W> AxisExt for (U, W)
where
    U: Deref<Target = T>,
    W: Deref<Target = T>,
{
    type El = T;

    fn main_axis(&self, dir: Direction) -> &Self::El {
        match dir {
            Direction::Horizontal => &self.0,
            Direction::Vertical => &self.1,
        }
    }

    fn cross_axis(&self, dir: Direction) -> &Self::El {
        match dir {
            Direction::Horizontal => &self.1,
            Direction::Vertical => &self.0,
        }
    }
}

impl<T, U, W> AxisExtMut for (U, W)
where
    U: DerefMut<Target = T>,
    W: DerefMut<Target = T>,
{
    fn main_axis_mut(&mut self, dir: Direction) -> &mut Self::El {
        match dir {
            Direction::Horizontal => self.0.deref_mut(),
            Direction::Vertical => self.1.deref_mut(),
        }
    }

    fn cross_axis_mut(&mut self, dir: Direction) -> &mut Self::El {
        match dir {
            Direction::Horizontal => &mut self.1,
            Direction::Vertical => &mut self.0,
        }
    }
}
